---
- hosts: all
  become: true

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: yes
      tags: prepare

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Pull image of "Redmine"
      community.docker.docker_image:
        name: redmine
        source: pull
        tag: latest
      tags: redmine

    - name: Copy env_file to container
      ansible.builtin.template:
        src: templates/.env.j2
        dest: /var/tmp/.env_redmine
      tags: redmine

    - name: Run "Redmine"
      community.docker.docker_container:
        name: some-redime
        image: redmine
        state: started
        restart_policy: unless-stopped
        ports:
          - "{{ app_port }}:3000"
        env_file: /var/tmp/.env_redmine
      tags: redmine

- hosts: webservers
  become: true
  tasks:

    - name: Install datadog
      ansible.builtin.import_role:
        name: datadog.datadog
      tags: datadog

    - name: Copy http_check to datadog
      ansible.builtin.template:
        src: templates/http_check.d/conf.yml.j2
        dest: /etc/datadog-agent/conf.d/http_check.d/redmine.yaml
        owner: "{{ datadog_user }}"
        group: "{{ datadog_group }}"
      tags: datadog