---
- name: Prepare servers
  hosts: all
  become: true

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: yes
      tags: prepare

  roles:
    - geerlingguy.pip

  tasks:
    - name: Install docker
      ansible.builtin.import_role:
        name: geerlingguy.docker
      when: install_docker is true

- name: Install Redmine
  hosts: webservers
  tasks:
    - name: Copy env_file to container
      ansible.builtin.template:
        src: templates/.env.j2
        dest: /var/tmp/.env_redmine
        mode: 0644
      tags: redmine

    - name: Run "Redmine"
      community.docker.docker_container:
        name: some-redime
        image: redmine
        restart_policy: unless-stopped
        ports:
          - "{{ app_port }}:3000"
        env_file: /var/tmp/.env_redmine6
      tags: redmine

- name: Install Datadog
  hosts: webservers
  become: true
  tasks:
    - name: Install datadog
      ansible.builtin.import_role:
        name: datadog.datadog
      tags: datadog

    - name: Copy http_check to datadog
      ansible.builtin.template:
        src: templates/http_check.d/conf.yml.j2
        dest: /etc/datadog-agent/conf.d/http_check.d/redmine.yaml
        owner: "{{ datadog_user }}"
        group: "{{ datadog_group }}"
        mode: 0644
      tags: datadog
