---
- hosts: all
  gather_facts: true
  become: true

  # vars:
  #   pip_install_packages:
  #     - name: docker

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: yes

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Pull image of "Redmine"
      community.docker.docker_image:
        name: redmine
        source: pull
        tag: latest
      tags: redmine

    # - name: Run "Redmine"
    #   community.docker.docker_container:
    #     name: some-redime
    #     image: redmine
