---
- hosts: all
  gather_facts: true
  become: true

  # vars:
  #   pip_install_packages:
  #     - name: docker

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: yes

  roles:
    - geerlingguy.pip