---
- hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: yes

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Pull image of "Redmine"
      community.docker.docker_image:
        name: redmine
        source: pull
        tag: latest
      tags: redmine

    - name: Copy env_file to container
      ansible.builtin.template:
        src: templates/.env.j2
        dest: /var/tmp/.env_redmine

    - name: Run "Redmine"
      community.docker.docker_container:
        name: some-redime
        image: redmine
        state: started
        ports:
          - "8000:3000"
        env_file: /var/tmp/.env_redmine
      tags: redmine
